### ISSUE TITLE
method /buyer/purchase return NULL !

### ISSUE THREAD

**Issue by sIiiS** [flowdee/envato-api-php-class#1]
Hello,

For first thank you for your great job!

I want to tell you that your code do not return correct info for `/buyer/purchase` method
Did you test it yourself ?
For me it return NULL but `/buyer/download` method work as well

**Comment by flowdee** [comment]
Thanks for the info @sIiiS, I'll have to take a look and update it

**Comment by sIiiS** [comment]
Hello,

Did you check it ?
Please inform me  about the issue

**Comment by flowdee** [comment]
Can you please try it directly via https://build.envato.com/api/#market_0_Buyer_Purchase ? Adding a purchase code on their site returns 0 as well, so it's not a thing of this API class.

Additionally you can try https://build.envato.com/api/#!/market_0/Author_Sale which in my case returns what I want.

**Comment by sIiiS** [comment]
Code in their site work as well but in your class not working and return some unreadable characters!

**Comment by flowdee** [comment]
Can you please send me an email ( click on the email at the bottom of my [site](http://flowdee.de/) ) with your code and the used credentials + purchase code so I can debug it? Right now I can't reproduce the error.

**Comment by sIiiS** [comment]
problem solved
it was because return in object not in string

**Comment by flowdee** [comment]
ok
